# Generated by Django 4.2.6 on 2024-03-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='state',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
